coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 0%
        base: auto 
        flags: 
          - unit
        paths: 
          - "src"
        if_ci_failed: ignore #success, failure, error, ignore
        informational: false
        only_pulls: false